version: 2
jobs:
  build:
    working_directory: ~/advocate-backend
    docker:
      - image: circleci/python:3.5.3

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt requirements-dev.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 ./

      - store_artifacts:
          path: test-reports
          destination: test-reports
